name = "CompatDevTools"
uuid = "732b9ffd-ba4a-45cb-82b2-a390f71ea5ac"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
OrderedCollections = "1.4"
julia = "1.4"
